# Generated by Django 3.0.3 on 2020-04-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_auto_20200406_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
